sudo: required
services:
    - docker

before_install:
    # tag name docker image la hungpnh/docker-react
    - docker build -t hungpnh/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true hungpnh/docker-react npm run test