sudo: required
services:
    - docker

before_install:
    # tag name docker image la hungpnh/docker-react
    - docker build -t hungpnh/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true hungpnh/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-1-841921761201"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_key_id: $AWS_SECRET_KEY